name: 기타 작업
description: 인프라, 문서, 빌드, 설정 등 기능도 버그도 아닌 것
title: "[Chore] "
labels: ["chore"]
body:
  - type: textarea
    id: what
    attributes:
      label: 할 일
      value: |
        - [ ] 
    validations:
      required: true

  - type: textarea
    id: why
    attributes:
      label: 이유
      description: 지금 무엇이 문제라서 이 작업이 필요한가
    validations:
      required: true
